apiVersion: "v1"
kind: "Template"
metadata:
  name: fluentd
  annotations:
    description: "Template to deploy fluentd haproxy service"
    tags: "infrastructure"
objects:
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: Exposes the elasticsearch server
    name: ${NAME}
  spec:
    ports:
    - name: elasticsearch
      port: 5140
      targetPort: 5140
    selector:
      name: ${NAME}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${NAME}
      spec:
        containers:
        - image: spinolacastro/fluentd-haproxy
          imagePullPolicy: IfNotPresent
          name: fluentd
          env:
          - name: STORAGE_ACCOUNT
            value: ${STORAGE_ACCOUNT}
          - name: STORAGE_ACCOUNT_ACCESS_KEY
            value: ${STORAGE_ACCOUNT_ACCESS_KEY}
          ports:
          - containerPort: 5140
            protocol: UDP
          terminationMessagePath: /dev/termination-log
          resources:
            limits:
              cpu: 1
          securityContext:
            privileged: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
parameters:
- name: NAME
  description: Fluentd service name
  required: true
  value: fluentd-haproxy
- name: STORAGE_ACCOUNT
  description: Storage Account Name
  required: true
  value: storageaccount
- name: STORAGE_ACCOUNT_ACCESS_KEY
  description: Storage Account Key
  required: true
  value: key