apiVersion: "v1"
kind: "Template"
metadata:
  name: fluentd
  annotations:
    description: "Template to deploy fluentd haproxy service"
    tags: "infrastructure"
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: fluentd-haproxy
    labels:
      template: fluentd-haproxy
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: Exposes the elasticsearch server
    name: ${NAME}
    labels:
      template: fluentd-haproxy
  spec:
    ports:
    - name: elasticsearch
      port: 5140
      targetPort: 5140
    selector:
      name: ${NAME}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: ${NAME}
    labels:
      template: fluentd-haproxy
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${NAME}
      spec:
        containers:
        - image: spinolacastro/fluentd-haproxy
          imagePullPolicy: IfNotPresent
          name: fluentd
          ports:
          - containerPort: 5140
            protocol: UDP
          resources: {}
          securityContext:
            capabilities: {}
          terminationMessagePath: /dev/termination-log
          resources:
            limits:
              cpu: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
parameters:
- name: NAME
  description: Fluentd service name
  required: true
  value: fluentd-haproxy